// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons/chunk.proto

package agrirouter.commons;

public final class Chunk {
  private Chunk() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChunkComponentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agrirouter.commons.ChunkComponent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * client generated unique identifier for larger binaries
     * </pre>
     *
     * <code>string context_id = 1;</code>
     */
    java.lang.String getContextId();
    /**
     * <pre>
     * client generated unique identifier for larger binaries
     * </pre>
     *
     * <code>string context_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getContextIdBytes();

    /**
     * <pre>
     * number of the current chunk 
     * </pre>
     *
     * <code>int64 current = 2;</code>
     */
    long getCurrent();

    /**
     * <pre>
     * total number of chunks of binary
     * </pre>
     *
     * <code>int64 total = 3;</code>
     */
    long getTotal();

    /**
     * <pre>
     * total size of binary
     * </pre>
     *
     * <code>int64 total_size = 4;</code>
     */
    long getTotalSize();
  }
  /**
   * Protobuf type {@code agrirouter.commons.ChunkComponent}
   */
  public  static final class ChunkComponent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agrirouter.commons.ChunkComponent)
      ChunkComponentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChunkComponent.newBuilder() to construct.
    private ChunkComponent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChunkComponent() {
      contextId_ = "";
      current_ = 0L;
      total_ = 0L;
      totalSize_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChunkComponent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              contextId_ = s;
              break;
            }
            case 16: {

              current_ = input.readInt64();
              break;
            }
            case 24: {

              total_ = input.readInt64();
              break;
            }
            case 32: {

              totalSize_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return agrirouter.commons.Chunk.internal_static_agrirouter_commons_ChunkComponent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return agrirouter.commons.Chunk.internal_static_agrirouter_commons_ChunkComponent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              agrirouter.commons.Chunk.ChunkComponent.class, agrirouter.commons.Chunk.ChunkComponent.Builder.class);
    }

    public static final int CONTEXT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object contextId_;
    /**
     * <pre>
     * client generated unique identifier for larger binaries
     * </pre>
     *
     * <code>string context_id = 1;</code>
     */
    public java.lang.String getContextId() {
      java.lang.Object ref = contextId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contextId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * client generated unique identifier for larger binaries
     * </pre>
     *
     * <code>string context_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextIdBytes() {
      java.lang.Object ref = contextId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contextId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENT_FIELD_NUMBER = 2;
    private long current_;
    /**
     * <pre>
     * number of the current chunk 
     * </pre>
     *
     * <code>int64 current = 2;</code>
     */
    public long getCurrent() {
      return current_;
    }

    public static final int TOTAL_FIELD_NUMBER = 3;
    private long total_;
    /**
     * <pre>
     * total number of chunks of binary
     * </pre>
     *
     * <code>int64 total = 3;</code>
     */
    public long getTotal() {
      return total_;
    }

    public static final int TOTAL_SIZE_FIELD_NUMBER = 4;
    private long totalSize_;
    /**
     * <pre>
     * total size of binary
     * </pre>
     *
     * <code>int64 total_size = 4;</code>
     */
    public long getTotalSize() {
      return totalSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContextIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contextId_);
      }
      if (current_ != 0L) {
        output.writeInt64(2, current_);
      }
      if (total_ != 0L) {
        output.writeInt64(3, total_);
      }
      if (totalSize_ != 0L) {
        output.writeInt64(4, totalSize_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContextIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contextId_);
      }
      if (current_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, current_);
      }
      if (total_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, total_);
      }
      if (totalSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, totalSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof agrirouter.commons.Chunk.ChunkComponent)) {
        return super.equals(obj);
      }
      agrirouter.commons.Chunk.ChunkComponent other = (agrirouter.commons.Chunk.ChunkComponent) obj;

      boolean result = true;
      result = result && getContextId()
          .equals(other.getContextId());
      result = result && (getCurrent()
          == other.getCurrent());
      result = result && (getTotal()
          == other.getTotal());
      result = result && (getTotalSize()
          == other.getTotalSize());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTEXT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getContextId().hashCode();
      hash = (37 * hash) + CURRENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrent());
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotal());
      hash = (37 * hash) + TOTAL_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalSize());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.commons.Chunk.ChunkComponent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(agrirouter.commons.Chunk.ChunkComponent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agrirouter.commons.ChunkComponent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agrirouter.commons.ChunkComponent)
        agrirouter.commons.Chunk.ChunkComponentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return agrirouter.commons.Chunk.internal_static_agrirouter_commons_ChunkComponent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return agrirouter.commons.Chunk.internal_static_agrirouter_commons_ChunkComponent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                agrirouter.commons.Chunk.ChunkComponent.class, agrirouter.commons.Chunk.ChunkComponent.Builder.class);
      }

      // Construct using agrirouter.commons.Chunk.ChunkComponent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        contextId_ = "";

        current_ = 0L;

        total_ = 0L;

        totalSize_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return agrirouter.commons.Chunk.internal_static_agrirouter_commons_ChunkComponent_descriptor;
      }

      public agrirouter.commons.Chunk.ChunkComponent getDefaultInstanceForType() {
        return agrirouter.commons.Chunk.ChunkComponent.getDefaultInstance();
      }

      public agrirouter.commons.Chunk.ChunkComponent build() {
        agrirouter.commons.Chunk.ChunkComponent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public agrirouter.commons.Chunk.ChunkComponent buildPartial() {
        agrirouter.commons.Chunk.ChunkComponent result = new agrirouter.commons.Chunk.ChunkComponent(this);
        result.contextId_ = contextId_;
        result.current_ = current_;
        result.total_ = total_;
        result.totalSize_ = totalSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof agrirouter.commons.Chunk.ChunkComponent) {
          return mergeFrom((agrirouter.commons.Chunk.ChunkComponent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(agrirouter.commons.Chunk.ChunkComponent other) {
        if (other == agrirouter.commons.Chunk.ChunkComponent.getDefaultInstance()) return this;
        if (!other.getContextId().isEmpty()) {
          contextId_ = other.contextId_;
          onChanged();
        }
        if (other.getCurrent() != 0L) {
          setCurrent(other.getCurrent());
        }
        if (other.getTotal() != 0L) {
          setTotal(other.getTotal());
        }
        if (other.getTotalSize() != 0L) {
          setTotalSize(other.getTotalSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        agrirouter.commons.Chunk.ChunkComponent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (agrirouter.commons.Chunk.ChunkComponent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object contextId_ = "";
      /**
       * <pre>
       * client generated unique identifier for larger binaries
       * </pre>
       *
       * <code>string context_id = 1;</code>
       */
      public java.lang.String getContextId() {
        java.lang.Object ref = contextId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contextId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * client generated unique identifier for larger binaries
       * </pre>
       *
       * <code>string context_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContextIdBytes() {
        java.lang.Object ref = contextId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contextId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * client generated unique identifier for larger binaries
       * </pre>
       *
       * <code>string context_id = 1;</code>
       */
      public Builder setContextId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contextId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client generated unique identifier for larger binaries
       * </pre>
       *
       * <code>string context_id = 1;</code>
       */
      public Builder clearContextId() {
        
        contextId_ = getDefaultInstance().getContextId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * client generated unique identifier for larger binaries
       * </pre>
       *
       * <code>string context_id = 1;</code>
       */
      public Builder setContextIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contextId_ = value;
        onChanged();
        return this;
      }

      private long current_ ;
      /**
       * <pre>
       * number of the current chunk 
       * </pre>
       *
       * <code>int64 current = 2;</code>
       */
      public long getCurrent() {
        return current_;
      }
      /**
       * <pre>
       * number of the current chunk 
       * </pre>
       *
       * <code>int64 current = 2;</code>
       */
      public Builder setCurrent(long value) {
        
        current_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * number of the current chunk 
       * </pre>
       *
       * <code>int64 current = 2;</code>
       */
      public Builder clearCurrent() {
        
        current_ = 0L;
        onChanged();
        return this;
      }

      private long total_ ;
      /**
       * <pre>
       * total number of chunks of binary
       * </pre>
       *
       * <code>int64 total = 3;</code>
       */
      public long getTotal() {
        return total_;
      }
      /**
       * <pre>
       * total number of chunks of binary
       * </pre>
       *
       * <code>int64 total = 3;</code>
       */
      public Builder setTotal(long value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * total number of chunks of binary
       * </pre>
       *
       * <code>int64 total = 3;</code>
       */
      public Builder clearTotal() {
        
        total_ = 0L;
        onChanged();
        return this;
      }

      private long totalSize_ ;
      /**
       * <pre>
       * total size of binary
       * </pre>
       *
       * <code>int64 total_size = 4;</code>
       */
      public long getTotalSize() {
        return totalSize_;
      }
      /**
       * <pre>
       * total size of binary
       * </pre>
       *
       * <code>int64 total_size = 4;</code>
       */
      public Builder setTotalSize(long value) {
        
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * total size of binary
       * </pre>
       *
       * <code>int64 total_size = 4;</code>
       */
      public Builder clearTotalSize() {
        
        totalSize_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:agrirouter.commons.ChunkComponent)
    }

    // @@protoc_insertion_point(class_scope:agrirouter.commons.ChunkComponent)
    private static final agrirouter.commons.Chunk.ChunkComponent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new agrirouter.commons.Chunk.ChunkComponent();
    }

    public static agrirouter.commons.Chunk.ChunkComponent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChunkComponent>
        PARSER = new com.google.protobuf.AbstractParser<ChunkComponent>() {
      public ChunkComponent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChunkComponent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChunkComponent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkComponent> getParserForType() {
      return PARSER;
    }

    public agrirouter.commons.Chunk.ChunkComponent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agrirouter_commons_ChunkComponent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agrirouter_commons_ChunkComponent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023commons/chunk.proto\022\022agrirouter.common" +
      "s\"X\n\016ChunkComponent\022\022\n\ncontext_id\030\001 \001(\t\022" +
      "\017\n\007current\030\002 \001(\003\022\r\n\005total\030\003 \001(\003\022\022\n\ntotal" +
      "_size\030\004 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_agrirouter_commons_ChunkComponent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agrirouter_commons_ChunkComponent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agrirouter_commons_ChunkComponent_descriptor,
        new java.lang.String[] { "ContextId", "Current", "Total", "TotalSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
