// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messaging/request/payload/feed/feed-requests.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Agrirouter.Feed.Request {

  /// <summary>Holder for reflection information generated from messaging/request/payload/feed/feed-requests.proto</summary>
  public static partial class FeedRequestsReflection {

    #region Descriptor
    /// <summary>File descriptor for messaging/request/payload/feed/feed-requests.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FeedRequestsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJtZXNzYWdpbmcvcmVxdWVzdC9wYXlsb2FkL2ZlZWQvZmVlZC1yZXF1ZXN0",
            "cy5wcm90bxIXYWdyaXJvdXRlci5mZWVkLnJlcXVlc3QaH2dvb2dsZS9wcm90",
            "b2J1Zi90aW1lc3RhbXAucHJvdG8ibAoOVmFsaWRpdHlQZXJpb2QSLQoJc2Vu",
            "dF9mcm9tGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIrCgdz",
            "ZW50X3RvGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJ2CgxN",
            "ZXNzYWdlUXVlcnkSEwoLbWVzc2FnZV9pZHMYASADKAkSDwoHc2VuZGVycxgC",
            "IAMoCRJACg92YWxpZGl0eV9wZXJpb2QYAyABKAsyJy5hZ3Jpcm91dGVyLmZl",
            "ZWQucmVxdWVzdC5WYWxpZGl0eVBlcmlvZCIlCg5NZXNzYWdlQ29uZmlybRIT",
            "CgttZXNzYWdlX2lkcxgBIAMoCSJ3Cg1NZXNzYWdlRGVsZXRlEhMKC21lc3Nh",
            "Z2VfaWRzGAEgAygJEg8KB3NlbmRlcnMYAiADKAkSQAoPdmFsaWRpdHlfcGVy",
            "aW9kGAMgASgLMicuYWdyaXJvdXRlci5mZWVkLnJlcXVlc3QuVmFsaWRpdHlQ",
            "ZXJpb2RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Agrirouter.Feed.Request.ValidityPeriod), global::Agrirouter.Feed.Request.ValidityPeriod.Parser, new[]{ "SentFrom", "SentTo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agrirouter.Feed.Request.MessageQuery), global::Agrirouter.Feed.Request.MessageQuery.Parser, new[]{ "MessageIds", "Senders", "ValidityPeriod" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agrirouter.Feed.Request.MessageConfirm), global::Agrirouter.Feed.Request.MessageConfirm.Parser, new[]{ "MessageIds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agrirouter.Feed.Request.MessageDelete), global::Agrirouter.Feed.Request.MessageDelete.Parser, new[]{ "MessageIds", "Senders", "ValidityPeriod" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ValidityPeriod : pb::IMessage<ValidityPeriod> {
    private static readonly pb::MessageParser<ValidityPeriod> _parser = new pb::MessageParser<ValidityPeriod>(() => new ValidityPeriod());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ValidityPeriod> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agrirouter.Feed.Request.FeedRequestsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidityPeriod() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidityPeriod(ValidityPeriod other) : this() {
      sentFrom_ = other.sentFrom_ != null ? other.sentFrom_.Clone() : null;
      sentTo_ = other.sentTo_ != null ? other.sentTo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidityPeriod Clone() {
      return new ValidityPeriod(this);
    }

    /// <summary>Field number for the "sent_from" field.</summary>
    public const int SentFromFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp sentFrom_;
    /// <summary>
    /// From date for the query should be UTC
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp SentFrom {
      get { return sentFrom_; }
      set {
        sentFrom_ = value;
      }
    }

    /// <summary>Field number for the "sent_to" field.</summary>
    public const int SentToFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp sentTo_;
    /// <summary>
    /// To date for the query should be UTC
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp SentTo {
      get { return sentTo_; }
      set {
        sentTo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ValidityPeriod);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ValidityPeriod other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SentFrom, other.SentFrom)) return false;
      if (!object.Equals(SentTo, other.SentTo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (sentFrom_ != null) hash ^= SentFrom.GetHashCode();
      if (sentTo_ != null) hash ^= SentTo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (sentFrom_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SentFrom);
      }
      if (sentTo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SentTo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (sentFrom_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SentFrom);
      }
      if (sentTo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SentTo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ValidityPeriod other) {
      if (other == null) {
        return;
      }
      if (other.sentFrom_ != null) {
        if (sentFrom_ == null) {
          SentFrom = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        SentFrom.MergeFrom(other.SentFrom);
      }
      if (other.sentTo_ != null) {
        if (sentTo_ == null) {
          SentTo = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        SentTo.MergeFrom(other.SentTo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (sentFrom_ == null) {
              SentFrom = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(SentFrom);
            break;
          }
          case 18: {
            if (sentTo_ == null) {
              SentTo = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(SentTo);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MessageQuery : pb::IMessage<MessageQuery> {
    private static readonly pb::MessageParser<MessageQuery> _parser = new pb::MessageParser<MessageQuery>(() => new MessageQuery());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageQuery> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agrirouter.Feed.Request.FeedRequestsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageQuery() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageQuery(MessageQuery other) : this() {
      messageIds_ = other.messageIds_.Clone();
      senders_ = other.senders_.Clone();
      validityPeriod_ = other.validityPeriod_ != null ? other.validityPeriod_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageQuery Clone() {
      return new MessageQuery(this);
    }

    /// <summary>Field number for the "message_ids" field.</summary>
    public const int MessageIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_messageIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> messageIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of agrirouter message IDs to specifically query for
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> MessageIds {
      get { return messageIds_; }
    }

    /// <summary>Field number for the "senders" field.</summary>
    public const int SendersFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_senders_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> senders_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of sender endpoint ID's to specifically query for
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Senders {
      get { return senders_; }
    }

    /// <summary>Field number for the "validity_period" field.</summary>
    public const int ValidityPeriodFieldNumber = 3;
    private global::Agrirouter.Feed.Request.ValidityPeriod validityPeriod_;
    /// <summary>
    /// The validity period for which to query within
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Agrirouter.Feed.Request.ValidityPeriod ValidityPeriod {
      get { return validityPeriod_; }
      set {
        validityPeriod_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageQuery);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageQuery other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!messageIds_.Equals(other.messageIds_)) return false;
      if(!senders_.Equals(other.senders_)) return false;
      if (!object.Equals(ValidityPeriod, other.ValidityPeriod)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= messageIds_.GetHashCode();
      hash ^= senders_.GetHashCode();
      if (validityPeriod_ != null) hash ^= ValidityPeriod.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      messageIds_.WriteTo(output, _repeated_messageIds_codec);
      senders_.WriteTo(output, _repeated_senders_codec);
      if (validityPeriod_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ValidityPeriod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += messageIds_.CalculateSize(_repeated_messageIds_codec);
      size += senders_.CalculateSize(_repeated_senders_codec);
      if (validityPeriod_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ValidityPeriod);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageQuery other) {
      if (other == null) {
        return;
      }
      messageIds_.Add(other.messageIds_);
      senders_.Add(other.senders_);
      if (other.validityPeriod_ != null) {
        if (validityPeriod_ == null) {
          ValidityPeriod = new global::Agrirouter.Feed.Request.ValidityPeriod();
        }
        ValidityPeriod.MergeFrom(other.ValidityPeriod);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            messageIds_.AddEntriesFrom(input, _repeated_messageIds_codec);
            break;
          }
          case 18: {
            senders_.AddEntriesFrom(input, _repeated_senders_codec);
            break;
          }
          case 26: {
            if (validityPeriod_ == null) {
              ValidityPeriod = new global::Agrirouter.Feed.Request.ValidityPeriod();
            }
            input.ReadMessage(ValidityPeriod);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MessageConfirm : pb::IMessage<MessageConfirm> {
    private static readonly pb::MessageParser<MessageConfirm> _parser = new pb::MessageParser<MessageConfirm>(() => new MessageConfirm());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageConfirm> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agrirouter.Feed.Request.FeedRequestsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageConfirm() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageConfirm(MessageConfirm other) : this() {
      messageIds_ = other.messageIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageConfirm Clone() {
      return new MessageConfirm(this);
    }

    /// <summary>Field number for the "message_ids" field.</summary>
    public const int MessageIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_messageIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> messageIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of agrirouter message ID's to confirm
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> MessageIds {
      get { return messageIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageConfirm);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageConfirm other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!messageIds_.Equals(other.messageIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= messageIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      messageIds_.WriteTo(output, _repeated_messageIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += messageIds_.CalculateSize(_repeated_messageIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageConfirm other) {
      if (other == null) {
        return;
      }
      messageIds_.Add(other.messageIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            messageIds_.AddEntriesFrom(input, _repeated_messageIds_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MessageDelete : pb::IMessage<MessageDelete> {
    private static readonly pb::MessageParser<MessageDelete> _parser = new pb::MessageParser<MessageDelete>(() => new MessageDelete());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MessageDelete> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agrirouter.Feed.Request.FeedRequestsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageDelete() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageDelete(MessageDelete other) : this() {
      messageIds_ = other.messageIds_.Clone();
      senders_ = other.senders_.Clone();
      validityPeriod_ = other.validityPeriod_ != null ? other.validityPeriod_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MessageDelete Clone() {
      return new MessageDelete(this);
    }

    /// <summary>Field number for the "message_ids" field.</summary>
    public const int MessageIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_messageIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> messageIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of agrirouter message ID's to delete
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> MessageIds {
      get { return messageIds_; }
    }

    /// <summary>Field number for the "senders" field.</summary>
    public const int SendersFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_senders_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> senders_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of sender endpoint ID's to consider for message deletion
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Senders {
      get { return senders_; }
    }

    /// <summary>Field number for the "validity_period" field.</summary>
    public const int ValidityPeriodFieldNumber = 3;
    private global::Agrirouter.Feed.Request.ValidityPeriod validityPeriod_;
    /// <summary>
    /// The validity period for which to delete all messages within
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Agrirouter.Feed.Request.ValidityPeriod ValidityPeriod {
      get { return validityPeriod_; }
      set {
        validityPeriod_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MessageDelete);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MessageDelete other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!messageIds_.Equals(other.messageIds_)) return false;
      if(!senders_.Equals(other.senders_)) return false;
      if (!object.Equals(ValidityPeriod, other.ValidityPeriod)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= messageIds_.GetHashCode();
      hash ^= senders_.GetHashCode();
      if (validityPeriod_ != null) hash ^= ValidityPeriod.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      messageIds_.WriteTo(output, _repeated_messageIds_codec);
      senders_.WriteTo(output, _repeated_senders_codec);
      if (validityPeriod_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ValidityPeriod);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += messageIds_.CalculateSize(_repeated_messageIds_codec);
      size += senders_.CalculateSize(_repeated_senders_codec);
      if (validityPeriod_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ValidityPeriod);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MessageDelete other) {
      if (other == null) {
        return;
      }
      messageIds_.Add(other.messageIds_);
      senders_.Add(other.senders_);
      if (other.validityPeriod_ != null) {
        if (validityPeriod_ == null) {
          ValidityPeriod = new global::Agrirouter.Feed.Request.ValidityPeriod();
        }
        ValidityPeriod.MergeFrom(other.ValidityPeriod);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            messageIds_.AddEntriesFrom(input, _repeated_messageIds_codec);
            break;
          }
          case 18: {
            senders_.AddEntriesFrom(input, _repeated_senders_codec);
            break;
          }
          case 26: {
            if (validityPeriod_ == null) {
              ValidityPeriod = new global::Agrirouter.Feed.Request.ValidityPeriod();
            }
            input.ReadMessage(ValidityPeriod);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
