// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/response/response.proto

package agrirouter.response;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agrirouter.response.ResponseEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * HTTP Response Codes will be used here (200, 400, 201, etc)
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     */
    int getResponseCode();

    /**
     * <pre>
     * The Type of the Body so that it can be decoded
     * </pre>
     *
     * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * The Type of the Body so that it can be decoded
     * </pre>
     *
     * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
     */
    agrirouter.response.Response.ResponseEnvelope.ResponseBodyType getType();

    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
     * </pre>
     *
     * <code>string application_message_id = 3;</code>
     */
    java.lang.String getApplicationMessageId();
    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
     * </pre>
     *
     * <code>string application_message_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getApplicationMessageIdBytes();

    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
     * </pre>
     *
     * <code>string message_id = 4;</code>
     */
    java.lang.String getMessageId();
    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
     * </pre>
     *
     * <code>string message_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <pre>
     * UTC Timestamp for when this acknowledgement was generated by the DH
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * UTC Timestamp for when this acknowledgement was generated by the DH
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <pre>
     * UTC Timestamp for when this acknowledgement was generated by the DH
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code agrirouter.response.ResponseEnvelope}
   */
  public  static final class ResponseEnvelope extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agrirouter.response.ResponseEnvelope)
      ResponseEnvelopeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseEnvelope.newBuilder() to construct.
    private ResponseEnvelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseEnvelope() {
      responseCode_ = 0;
      type_ = 0;
      applicationMessageId_ = "";
      messageId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              responseCode_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              applicationMessageId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return agrirouter.response.Response.internal_static_agrirouter_response_ResponseEnvelope_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return agrirouter.response.Response.internal_static_agrirouter_response_ResponseEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              agrirouter.response.Response.ResponseEnvelope.class, agrirouter.response.Response.ResponseEnvelope.Builder.class);
    }

    /**
     * Protobuf enum {@code agrirouter.response.ResponseEnvelope.ResponseBodyType}
     */
    public enum ResponseBodyType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MESSAGES = 0;</code>
       */
      MESSAGES(0),
      /**
       * <pre>
       * Represents a successful acknowledgement of a message sent to the agrirouter
       * </pre>
       *
       * <code>ACK = 1;</code>
       */
      ACK(1),
      /**
       * <pre>
       * Represents a successful acknowledgement of a message sent to the agrirouter but contains some info or warn messages back
       * </pre>
       *
       * <code>ACK_WITH_MESSAGES = 2;</code>
       */
      ACK_WITH_MESSAGES(2),
      /**
       * <pre>
       * Represents a failure response in correlation to a message sent to the agrirouter
       * </pre>
       *
       * <code>ACK_WITH_FAILURE = 3;</code>
       */
      ACK_WITH_FAILURE(3),
      /**
       * <pre>
       * Used for acknowledgements for feed envelope requests and cantain the agrirouter.feed.response.EnvelopeResponse details
       * </pre>
       *
       * <code>ACK_FOR_FEED_HEADER_LIST = 6;</code>
       */
      ACK_FOR_FEED_HEADER_LIST(6),
      /**
       * <pre>
       * Used for acknowledgements for feed payload requests and cantain the agrirouter.feed.response.PayloadResponse details
       * </pre>
       *
       * <code>ACK_FOR_FEED_MESSAGE = 7;</code>
       */
      ACK_FOR_FEED_MESSAGE(7),
      /**
       * <pre>
       * Response for failed requests to feed queries
       * </pre>
       *
       * <code>ACK_FOR_FEED_FAILED_MESSAGE = 8;</code>
       */
      ACK_FOR_FEED_FAILED_MESSAGE(8),
      /**
       * <pre>
       * Used for a response which contains the endpoint listing query results
       * </pre>
       *
       * <code>ENDPOINTS_LISTING = 10;</code>
       */
      ENDPOINTS_LISTING(10),
      /**
       * <pre>
       * Used for the response body type for agrirouter.cloud.registration.OnboardingResponse
       * </pre>
       *
       * <code>CLOUD_REGISTRATIONS = 11;</code>
       */
      CLOUD_REGISTRATIONS(11),
      /**
       * <pre>
       * Used for push notification messages
       * </pre>
       *
       * <code>PUSH_NOTIFICATION = 12;</code>
       */
      PUSH_NOTIFICATION(12),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MESSAGES = 0;</code>
       */
      public static final int MESSAGES_VALUE = 0;
      /**
       * <pre>
       * Represents a successful acknowledgement of a message sent to the agrirouter
       * </pre>
       *
       * <code>ACK = 1;</code>
       */
      public static final int ACK_VALUE = 1;
      /**
       * <pre>
       * Represents a successful acknowledgement of a message sent to the agrirouter but contains some info or warn messages back
       * </pre>
       *
       * <code>ACK_WITH_MESSAGES = 2;</code>
       */
      public static final int ACK_WITH_MESSAGES_VALUE = 2;
      /**
       * <pre>
       * Represents a failure response in correlation to a message sent to the agrirouter
       * </pre>
       *
       * <code>ACK_WITH_FAILURE = 3;</code>
       */
      public static final int ACK_WITH_FAILURE_VALUE = 3;
      /**
       * <pre>
       * Used for acknowledgements for feed envelope requests and cantain the agrirouter.feed.response.EnvelopeResponse details
       * </pre>
       *
       * <code>ACK_FOR_FEED_HEADER_LIST = 6;</code>
       */
      public static final int ACK_FOR_FEED_HEADER_LIST_VALUE = 6;
      /**
       * <pre>
       * Used for acknowledgements for feed payload requests and cantain the agrirouter.feed.response.PayloadResponse details
       * </pre>
       *
       * <code>ACK_FOR_FEED_MESSAGE = 7;</code>
       */
      public static final int ACK_FOR_FEED_MESSAGE_VALUE = 7;
      /**
       * <pre>
       * Response for failed requests to feed queries
       * </pre>
       *
       * <code>ACK_FOR_FEED_FAILED_MESSAGE = 8;</code>
       */
      public static final int ACK_FOR_FEED_FAILED_MESSAGE_VALUE = 8;
      /**
       * <pre>
       * Used for a response which contains the endpoint listing query results
       * </pre>
       *
       * <code>ENDPOINTS_LISTING = 10;</code>
       */
      public static final int ENDPOINTS_LISTING_VALUE = 10;
      /**
       * <pre>
       * Used for the response body type for agrirouter.cloud.registration.OnboardingResponse
       * </pre>
       *
       * <code>CLOUD_REGISTRATIONS = 11;</code>
       */
      public static final int CLOUD_REGISTRATIONS_VALUE = 11;
      /**
       * <pre>
       * Used for push notification messages
       * </pre>
       *
       * <code>PUSH_NOTIFICATION = 12;</code>
       */
      public static final int PUSH_NOTIFICATION_VALUE = 12;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseBodyType valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseBodyType forNumber(int value) {
        switch (value) {
          case 0: return MESSAGES;
          case 1: return ACK;
          case 2: return ACK_WITH_MESSAGES;
          case 3: return ACK_WITH_FAILURE;
          case 6: return ACK_FOR_FEED_HEADER_LIST;
          case 7: return ACK_FOR_FEED_MESSAGE;
          case 8: return ACK_FOR_FEED_FAILED_MESSAGE;
          case 10: return ENDPOINTS_LISTING;
          case 11: return CLOUD_REGISTRATIONS;
          case 12: return PUSH_NOTIFICATION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseBodyType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResponseBodyType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseBodyType>() {
              public ResponseBodyType findValueByNumber(int number) {
                return ResponseBodyType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return agrirouter.response.Response.ResponseEnvelope.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResponseBodyType[] VALUES = values();

      public static ResponseBodyType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResponseBodyType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:agrirouter.response.ResponseEnvelope.ResponseBodyType)
    }

    public static final int RESPONSE_CODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <pre>
     * HTTP Response Codes will be used here (200, 400, 201, etc)
     * </pre>
     *
     * <code>int32 response_code = 1;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     * The Type of the Body so that it can be decoded
     * </pre>
     *
     * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * The Type of the Body so that it can be decoded
     * </pre>
     *
     * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
     */
    public agrirouter.response.Response.ResponseEnvelope.ResponseBodyType getType() {
      agrirouter.response.Response.ResponseEnvelope.ResponseBodyType result = agrirouter.response.Response.ResponseEnvelope.ResponseBodyType.valueOf(type_);
      return result == null ? agrirouter.response.Response.ResponseEnvelope.ResponseBodyType.UNRECOGNIZED : result;
    }

    public static final int APPLICATION_MESSAGE_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object applicationMessageId_;
    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
     * </pre>
     *
     * <code>string application_message_id = 3;</code>
     */
    public java.lang.String getApplicationMessageId() {
      java.lang.Object ref = applicationMessageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationMessageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
     * </pre>
     *
     * <code>string application_message_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getApplicationMessageIdBytes() {
      java.lang.Object ref = applicationMessageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object messageId_;
    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
     * </pre>
     *
     * <code>string message_id = 4;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
     * </pre>
     *
     * <code>string message_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <pre>
     * UTC Timestamp for when this acknowledgement was generated by the DH
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <pre>
     * UTC Timestamp for when this acknowledgement was generated by the DH
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <pre>
     * UTC Timestamp for when this acknowledgement was generated by the DH
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (responseCode_ != 0) {
        output.writeInt32(1, responseCode_);
      }
      if (type_ != agrirouter.response.Response.ResponseEnvelope.ResponseBodyType.MESSAGES.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getApplicationMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, applicationMessageId_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageId_);
      }
      if (timestamp_ != null) {
        output.writeMessage(5, getTimestamp());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, responseCode_);
      }
      if (type_ != agrirouter.response.Response.ResponseEnvelope.ResponseBodyType.MESSAGES.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getApplicationMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, applicationMessageId_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageId_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTimestamp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof agrirouter.response.Response.ResponseEnvelope)) {
        return super.equals(obj);
      }
      agrirouter.response.Response.ResponseEnvelope other = (agrirouter.response.Response.ResponseEnvelope) obj;

      boolean result = true;
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && type_ == other.type_;
      result = result && getApplicationMessageId()
          .equals(other.getApplicationMessageId());
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + APPLICATION_MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationMessageId().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.response.Response.ResponseEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(agrirouter.response.Response.ResponseEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agrirouter.response.ResponseEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agrirouter.response.ResponseEnvelope)
        agrirouter.response.Response.ResponseEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return agrirouter.response.Response.internal_static_agrirouter_response_ResponseEnvelope_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return agrirouter.response.Response.internal_static_agrirouter_response_ResponseEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                agrirouter.response.Response.ResponseEnvelope.class, agrirouter.response.Response.ResponseEnvelope.Builder.class);
      }

      // Construct using agrirouter.response.Response.ResponseEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseCode_ = 0;

        type_ = 0;

        applicationMessageId_ = "";

        messageId_ = "";

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return agrirouter.response.Response.internal_static_agrirouter_response_ResponseEnvelope_descriptor;
      }

      public agrirouter.response.Response.ResponseEnvelope getDefaultInstanceForType() {
        return agrirouter.response.Response.ResponseEnvelope.getDefaultInstance();
      }

      public agrirouter.response.Response.ResponseEnvelope build() {
        agrirouter.response.Response.ResponseEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public agrirouter.response.Response.ResponseEnvelope buildPartial() {
        agrirouter.response.Response.ResponseEnvelope result = new agrirouter.response.Response.ResponseEnvelope(this);
        result.responseCode_ = responseCode_;
        result.type_ = type_;
        result.applicationMessageId_ = applicationMessageId_;
        result.messageId_ = messageId_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof agrirouter.response.Response.ResponseEnvelope) {
          return mergeFrom((agrirouter.response.Response.ResponseEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(agrirouter.response.Response.ResponseEnvelope other) {
        if (other == agrirouter.response.Response.ResponseEnvelope.getDefaultInstance()) return this;
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getApplicationMessageId().isEmpty()) {
          applicationMessageId_ = other.applicationMessageId_;
          onChanged();
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        agrirouter.response.Response.ResponseEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (agrirouter.response.Response.ResponseEnvelope) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int responseCode_ ;
      /**
       * <pre>
       * HTTP Response Codes will be used here (200, 400, 201, etc)
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <pre>
       * HTTP Response Codes will be used here (200, 400, 201, etc)
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * HTTP Response Codes will be used here (200, 400, 201, etc)
       * </pre>
       *
       * <code>int32 response_code = 1;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * The Type of the Body so that it can be decoded
       * </pre>
       *
       * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * The Type of the Body so that it can be decoded
       * </pre>
       *
       * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Type of the Body so that it can be decoded
       * </pre>
       *
       * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
       */
      public agrirouter.response.Response.ResponseEnvelope.ResponseBodyType getType() {
        agrirouter.response.Response.ResponseEnvelope.ResponseBodyType result = agrirouter.response.Response.ResponseEnvelope.ResponseBodyType.valueOf(type_);
        return result == null ? agrirouter.response.Response.ResponseEnvelope.ResponseBodyType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The Type of the Body so that it can be decoded
       * </pre>
       *
       * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
       */
      public Builder setType(agrirouter.response.Response.ResponseEnvelope.ResponseBodyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The Type of the Body so that it can be decoded
       * </pre>
       *
       * <code>.agrirouter.response.ResponseEnvelope.ResponseBodyType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object applicationMessageId_ = "";
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
       * </pre>
       *
       * <code>string application_message_id = 3;</code>
       */
      public java.lang.String getApplicationMessageId() {
        java.lang.Object ref = applicationMessageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          applicationMessageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
       * </pre>
       *
       * <code>string application_message_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getApplicationMessageIdBytes() {
        java.lang.Object ref = applicationMessageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          applicationMessageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
       * </pre>
       *
       * <code>string application_message_id = 3;</code>
       */
      public Builder setApplicationMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        applicationMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
       * </pre>
       *
       * <code>string application_message_id = 3;</code>
       */
      public Builder clearApplicationMessageId() {
        
        applicationMessageId_ = getDefaultInstance().getApplicationMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter this ID could be placed here as it was sent by the application
       * </pre>
       *
       * <code>string application_message_id = 3;</code>
       */
      public Builder setApplicationMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        applicationMessageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
       * </pre>
       *
       * <code>string message_id = 4;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
       * </pre>
       *
       * <code>string message_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
       * </pre>
       *
       * <code>string message_id = 4;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
       * </pre>
       *
       * <code>string message_id = 4;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If this is in reference to a message received by the agrirouter the generated agrirouter ID would be here in reference
       * </pre>
       *
       * <code>string message_id = 4;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <pre>
       * UTC Timestamp for when this acknowledgement was generated by the DH
       * </pre>
       *
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:agrirouter.response.ResponseEnvelope)
    }

    // @@protoc_insertion_point(class_scope:agrirouter.response.ResponseEnvelope)
    private static final agrirouter.response.Response.ResponseEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new agrirouter.response.Response.ResponseEnvelope();
    }

    public static agrirouter.response.Response.ResponseEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<ResponseEnvelope>() {
      public ResponseEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseEnvelope(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseEnvelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseEnvelope> getParserForType() {
      return PARSER;
    }

    public agrirouter.response.Response.ResponseEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponsePayloadWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agrirouter.response.ResponsePayloadWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    boolean hasDetails();
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    com.google.protobuf.Any getDetails();
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getDetailsOrBuilder();
  }
  /**
   * Protobuf type {@code agrirouter.response.ResponsePayloadWrapper}
   */
  public  static final class ResponsePayloadWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agrirouter.response.ResponsePayloadWrapper)
      ResponsePayloadWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponsePayloadWrapper.newBuilder() to construct.
    private ResponsePayloadWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponsePayloadWrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponsePayloadWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (details_ != null) {
                subBuilder = details_.toBuilder();
              }
              details_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(details_);
                details_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return agrirouter.response.Response.internal_static_agrirouter_response_ResponsePayloadWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return agrirouter.response.Response.internal_static_agrirouter_response_ResponsePayloadWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              agrirouter.response.Response.ResponsePayloadWrapper.class, agrirouter.response.Response.ResponsePayloadWrapper.Builder.class);
    }

    public static final int DETAILS_FIELD_NUMBER = 1;
    private com.google.protobuf.Any details_;
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    public boolean hasDetails() {
      return details_ != null;
    }
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    public com.google.protobuf.Any getDetails() {
      return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
    }
    /**
     * <code>.google.protobuf.Any details = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
      return getDetails();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (details_ != null) {
        output.writeMessage(1, getDetails());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (details_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDetails());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof agrirouter.response.Response.ResponsePayloadWrapper)) {
        return super.equals(obj);
      }
      agrirouter.response.Response.ResponsePayloadWrapper other = (agrirouter.response.Response.ResponsePayloadWrapper) obj;

      boolean result = true;
      result = result && (hasDetails() == other.hasDetails());
      if (hasDetails()) {
        result = result && getDetails()
            .equals(other.getDetails());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDetails()) {
        hash = (37 * hash) + DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getDetails().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.response.Response.ResponsePayloadWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(agrirouter.response.Response.ResponsePayloadWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agrirouter.response.ResponsePayloadWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agrirouter.response.ResponsePayloadWrapper)
        agrirouter.response.Response.ResponsePayloadWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return agrirouter.response.Response.internal_static_agrirouter_response_ResponsePayloadWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return agrirouter.response.Response.internal_static_agrirouter_response_ResponsePayloadWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                agrirouter.response.Response.ResponsePayloadWrapper.class, agrirouter.response.Response.ResponsePayloadWrapper.Builder.class);
      }

      // Construct using agrirouter.response.Response.ResponsePayloadWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (detailsBuilder_ == null) {
          details_ = null;
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return agrirouter.response.Response.internal_static_agrirouter_response_ResponsePayloadWrapper_descriptor;
      }

      public agrirouter.response.Response.ResponsePayloadWrapper getDefaultInstanceForType() {
        return agrirouter.response.Response.ResponsePayloadWrapper.getDefaultInstance();
      }

      public agrirouter.response.Response.ResponsePayloadWrapper build() {
        agrirouter.response.Response.ResponsePayloadWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public agrirouter.response.Response.ResponsePayloadWrapper buildPartial() {
        agrirouter.response.Response.ResponsePayloadWrapper result = new agrirouter.response.Response.ResponsePayloadWrapper(this);
        if (detailsBuilder_ == null) {
          result.details_ = details_;
        } else {
          result.details_ = detailsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof agrirouter.response.Response.ResponsePayloadWrapper) {
          return mergeFrom((agrirouter.response.Response.ResponsePayloadWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(agrirouter.response.Response.ResponsePayloadWrapper other) {
        if (other == agrirouter.response.Response.ResponsePayloadWrapper.getDefaultInstance()) return this;
        if (other.hasDetails()) {
          mergeDetails(other.getDetails());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        agrirouter.response.Response.ResponsePayloadWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (agrirouter.response.Response.ResponsePayloadWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Any details_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public boolean hasDetails() {
        return detailsBuilder_ != null || details_ != null;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public com.google.protobuf.Any getDetails() {
        if (detailsBuilder_ == null) {
          return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
        } else {
          return detailsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder setDetails(com.google.protobuf.Any value) {
        if (detailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          details_ = value;
          onChanged();
        } else {
          detailsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder setDetails(
          com.google.protobuf.Any.Builder builderForValue) {
        if (detailsBuilder_ == null) {
          details_ = builderForValue.build();
          onChanged();
        } else {
          detailsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder mergeDetails(com.google.protobuf.Any value) {
        if (detailsBuilder_ == null) {
          if (details_ != null) {
            details_ =
              com.google.protobuf.Any.newBuilder(details_).mergeFrom(value).buildPartial();
          } else {
            details_ = value;
          }
          onChanged();
        } else {
          detailsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public Builder clearDetails() {
        if (detailsBuilder_ == null) {
          details_ = null;
          onChanged();
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public com.google.protobuf.Any.Builder getDetailsBuilder() {
        
        onChanged();
        return getDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
        if (detailsBuilder_ != null) {
          return detailsBuilder_.getMessageOrBuilder();
        } else {
          return details_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : details_;
        }
      }
      /**
       * <code>.google.protobuf.Any details = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDetailsFieldBuilder() {
        if (detailsBuilder_ == null) {
          detailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getDetails(),
                  getParentForChildren(),
                  isClean());
          details_ = null;
        }
        return detailsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:agrirouter.response.ResponsePayloadWrapper)
    }

    // @@protoc_insertion_point(class_scope:agrirouter.response.ResponsePayloadWrapper)
    private static final agrirouter.response.Response.ResponsePayloadWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new agrirouter.response.Response.ResponsePayloadWrapper();
    }

    public static agrirouter.response.Response.ResponsePayloadWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponsePayloadWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ResponsePayloadWrapper>() {
      public ResponsePayloadWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponsePayloadWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponsePayloadWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponsePayloadWrapper> getParserForType() {
      return PARSER;
    }

    public agrirouter.response.Response.ResponsePayloadWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agrirouter_response_ResponseEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agrirouter_response_ResponseEnvelope_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agrirouter_response_ResponsePayloadWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agrirouter_response_ResponsePayloadWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!messaging/response/response.proto\022\023agr" +
      "irouter.response\032\031google/protobuf/any.pr" +
      "oto\032\037google/protobuf/timestamp.proto\"\313\003\n" +
      "\020ResponseEnvelope\022\025\n\rresponse_code\030\001 \001(\005" +
      "\022D\n\004type\030\002 \001(\01626.agrirouter.response.Res" +
      "ponseEnvelope.ResponseBodyType\022\036\n\026applic" +
      "ation_message_id\030\003 \001(\t\022\022\n\nmessage_id\030\004 \001" +
      "(\t\022-\n\ttimestamp\030\005 \001(\0132\032.google.protobuf." +
      "Timestamp\"\366\001\n\020ResponseBodyType\022\014\n\010MESSAG" +
      "ES\020\000\022\007\n\003ACK\020\001\022\025\n\021ACK_WITH_MESSAGES\020\002\022\024\n\020" +
      "ACK_WITH_FAILURE\020\003\022\034\n\030ACK_FOR_FEED_HEADE" +
      "R_LIST\020\006\022\030\n\024ACK_FOR_FEED_MESSAGE\020\007\022\037\n\033AC" +
      "K_FOR_FEED_FAILED_MESSAGE\020\010\022\025\n\021ENDPOINTS" +
      "_LISTING\020\n\022\027\n\023CLOUD_REGISTRATIONS\020\013\022\025\n\021P" +
      "USH_NOTIFICATION\020\014\"?\n\026ResponsePayloadWra" +
      "pper\022%\n\007details\030\001 \001(\0132\024.google.protobuf." +
      "Anyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_agrirouter_response_ResponseEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agrirouter_response_ResponseEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agrirouter_response_ResponseEnvelope_descriptor,
        new java.lang.String[] { "ResponseCode", "Type", "ApplicationMessageId", "MessageId", "Timestamp", });
    internal_static_agrirouter_response_ResponsePayloadWrapper_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_agrirouter_response_ResponsePayloadWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agrirouter_response_ResponsePayloadWrapper_descriptor,
        new java.lang.String[] { "Details", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
