// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/response/payload/endpoint/capability.proto

package agrirouter.response.payload.endpoint;

public final class Capability {
  private Capability() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CapabilityResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agrirouter.response.payload.endpoint.CapabilityResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Used for unique identification of the message for the application
     * </pre>
     *
     * <code>string application_message_id = 1;</code>
     */
    java.lang.String getApplicationMessageId();
    /**
     * <pre>
     * Used for unique identification of the message for the application
     * </pre>
     *
     * <code>string application_message_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getApplicationMessageIdBytes();

    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    java.util.List<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient> 
        getRecipientsList();
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient getRecipients(int index);
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    int getRecipientsCount();
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    java.util.List<? extends agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder> 
        getRecipientsOrBuilderList();
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder getRecipientsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code agrirouter.response.payload.endpoint.CapabilityResponse}
   */
  public  static final class CapabilityResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agrirouter.response.payload.endpoint.CapabilityResponse)
      CapabilityResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CapabilityResponse.newBuilder() to construct.
    private CapabilityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CapabilityResponse() {
      applicationMessageId_ = "";
      recipients_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CapabilityResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              applicationMessageId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                recipients_ = new java.util.ArrayList<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient>();
                mutable_bitField0_ |= 0x00000002;
              }
              recipients_.add(
                  input.readMessage(agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          recipients_ = java.util.Collections.unmodifiableList(recipients_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              agrirouter.response.payload.endpoint.Capability.CapabilityResponse.class, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Builder.class);
    }

    public interface RecipientOrBuilder extends
        // @@protoc_insertion_point(interface_extends:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string id = 1;</code>
       */
      java.lang.String getId();
      /**
       * <code>string id = 1;</code>
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      java.util.List<java.lang.String>
          getTechnicalMessageTypeList();
      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      int getTechnicalMessageTypeCount();
      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      java.lang.String getTechnicalMessageType(int index);
      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      com.google.protobuf.ByteString
          getTechnicalMessageTypeBytes(int index);
    }
    /**
     * Protobuf type {@code agrirouter.response.payload.endpoint.CapabilityResponse.Recipient}
     */
    public  static final class Recipient extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
        RecipientOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Recipient.newBuilder() to construct.
      private Recipient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Recipient() {
        id_ = "";
        technicalMessageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Recipient(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                id_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  technicalMessageType_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                technicalMessageType_.add(s);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            technicalMessageType_ = technicalMessageType_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.class, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private volatile java.lang.Object id_;
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TECHNICAL_MESSAGE_TYPE_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList technicalMessageType_;
      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTechnicalMessageTypeList() {
        return technicalMessageType_;
      }
      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      public int getTechnicalMessageTypeCount() {
        return technicalMessageType_.size();
      }
      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      public java.lang.String getTechnicalMessageType(int index) {
        return technicalMessageType_.get(index);
      }
      /**
       * <code>repeated string technical_message_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTechnicalMessageTypeBytes(int index) {
        return technicalMessageType_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
        }
        for (int i = 0; i < technicalMessageType_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, technicalMessageType_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < technicalMessageType_.size(); i++) {
            dataSize += computeStringSizeNoTag(technicalMessageType_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getTechnicalMessageTypeList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient)) {
          return super.equals(obj);
        }
        agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient other = (agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient) obj;

        boolean result = true;
        result = result && getId()
            .equals(other.getId());
        result = result && getTechnicalMessageTypeList()
            .equals(other.getTechnicalMessageTypeList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        if (getTechnicalMessageTypeCount() > 0) {
          hash = (37 * hash) + TECHNICAL_MESSAGE_TYPE_FIELD_NUMBER;
          hash = (53 * hash) + getTechnicalMessageTypeList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code agrirouter.response.payload.endpoint.CapabilityResponse.Recipient}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
          agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.class, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder.class);
        }

        // Construct using agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          id_ = "";

          technicalMessageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_descriptor;
        }

        public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient getDefaultInstanceForType() {
          return agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.getDefaultInstance();
        }

        public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient build() {
          agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient buildPartial() {
          agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient result = new agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.id_ = id_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            technicalMessageType_ = technicalMessageType_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.technicalMessageType_ = technicalMessageType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient) {
            return mergeFrom((agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient other) {
          if (other == agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.getDefaultInstance()) return this;
          if (!other.getId().isEmpty()) {
            id_ = other.id_;
            onChanged();
          }
          if (!other.technicalMessageType_.isEmpty()) {
            if (technicalMessageType_.isEmpty()) {
              technicalMessageType_ = other.technicalMessageType_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTechnicalMessageTypeIsMutable();
              technicalMessageType_.addAll(other.technicalMessageType_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object id_ = "";
        /**
         * <code>string id = 1;</code>
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string id = 1;</code>
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>string id = 1;</code>
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          id_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList technicalMessageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureTechnicalMessageTypeIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            technicalMessageType_ = new com.google.protobuf.LazyStringArrayList(technicalMessageType_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getTechnicalMessageTypeList() {
          return technicalMessageType_.getUnmodifiableView();
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public int getTechnicalMessageTypeCount() {
          return technicalMessageType_.size();
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public java.lang.String getTechnicalMessageType(int index) {
          return technicalMessageType_.get(index);
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTechnicalMessageTypeBytes(int index) {
          return technicalMessageType_.getByteString(index);
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public Builder setTechnicalMessageType(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTechnicalMessageTypeIsMutable();
          technicalMessageType_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public Builder addTechnicalMessageType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureTechnicalMessageTypeIsMutable();
          technicalMessageType_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public Builder addAllTechnicalMessageType(
            java.lang.Iterable<java.lang.String> values) {
          ensureTechnicalMessageTypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, technicalMessageType_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public Builder clearTechnicalMessageType() {
          technicalMessageType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string technical_message_type = 2;</code>
         */
        public Builder addTechnicalMessageTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureTechnicalMessageTypeIsMutable();
          technicalMessageType_.add(value);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
      }

      // @@protoc_insertion_point(class_scope:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
      private static final agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient();
      }

      public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Recipient>
          PARSER = new com.google.protobuf.AbstractParser<Recipient>() {
        public Recipient parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Recipient(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Recipient> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Recipient> getParserForType() {
        return PARSER;
      }

      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int APPLICATION_MESSAGE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object applicationMessageId_;
    /**
     * <pre>
     * Used for unique identification of the message for the application
     * </pre>
     *
     * <code>string application_message_id = 1;</code>
     */
    public java.lang.String getApplicationMessageId() {
      java.lang.Object ref = applicationMessageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationMessageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Used for unique identification of the message for the application
     * </pre>
     *
     * <code>string application_message_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getApplicationMessageIdBytes() {
      java.lang.Object ref = applicationMessageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECIPIENTS_FIELD_NUMBER = 2;
    private java.util.List<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient> recipients_;
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    public java.util.List<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient> getRecipientsList() {
      return recipients_;
    }
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    public java.util.List<? extends agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder> 
        getRecipientsOrBuilderList() {
      return recipients_;
    }
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    public int getRecipientsCount() {
      return recipients_.size();
    }
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient getRecipients(int index) {
      return recipients_.get(index);
    }
    /**
     * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
     */
    public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder getRecipientsOrBuilder(
        int index) {
      return recipients_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getApplicationMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, applicationMessageId_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        output.writeMessage(2, recipients_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getApplicationMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, applicationMessageId_);
      }
      for (int i = 0; i < recipients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, recipients_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof agrirouter.response.payload.endpoint.Capability.CapabilityResponse)) {
        return super.equals(obj);
      }
      agrirouter.response.payload.endpoint.Capability.CapabilityResponse other = (agrirouter.response.payload.endpoint.Capability.CapabilityResponse) obj;

      boolean result = true;
      result = result && getApplicationMessageId()
          .equals(other.getApplicationMessageId());
      result = result && getRecipientsList()
          .equals(other.getRecipientsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPLICATION_MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationMessageId().hashCode();
      if (getRecipientsCount() > 0) {
        hash = (37 * hash) + RECIPIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getRecipientsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(agrirouter.response.payload.endpoint.Capability.CapabilityResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agrirouter.response.payload.endpoint.CapabilityResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agrirouter.response.payload.endpoint.CapabilityResponse)
        agrirouter.response.payload.endpoint.Capability.CapabilityResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                agrirouter.response.payload.endpoint.Capability.CapabilityResponse.class, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Builder.class);
      }

      // Construct using agrirouter.response.payload.endpoint.Capability.CapabilityResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecipientsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        applicationMessageId_ = "";

        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return agrirouter.response.payload.endpoint.Capability.internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_descriptor;
      }

      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse getDefaultInstanceForType() {
        return agrirouter.response.payload.endpoint.Capability.CapabilityResponse.getDefaultInstance();
      }

      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse build() {
        agrirouter.response.payload.endpoint.Capability.CapabilityResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse buildPartial() {
        agrirouter.response.payload.endpoint.Capability.CapabilityResponse result = new agrirouter.response.payload.endpoint.Capability.CapabilityResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.applicationMessageId_ = applicationMessageId_;
        if (recipientsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            recipients_ = java.util.Collections.unmodifiableList(recipients_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.recipients_ = recipients_;
        } else {
          result.recipients_ = recipientsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof agrirouter.response.payload.endpoint.Capability.CapabilityResponse) {
          return mergeFrom((agrirouter.response.payload.endpoint.Capability.CapabilityResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(agrirouter.response.payload.endpoint.Capability.CapabilityResponse other) {
        if (other == agrirouter.response.payload.endpoint.Capability.CapabilityResponse.getDefaultInstance()) return this;
        if (!other.getApplicationMessageId().isEmpty()) {
          applicationMessageId_ = other.applicationMessageId_;
          onChanged();
        }
        if (recipientsBuilder_ == null) {
          if (!other.recipients_.isEmpty()) {
            if (recipients_.isEmpty()) {
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRecipientsIsMutable();
              recipients_.addAll(other.recipients_);
            }
            onChanged();
          }
        } else {
          if (!other.recipients_.isEmpty()) {
            if (recipientsBuilder_.isEmpty()) {
              recipientsBuilder_.dispose();
              recipientsBuilder_ = null;
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000002);
              recipientsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecipientsFieldBuilder() : null;
            } else {
              recipientsBuilder_.addAllMessages(other.recipients_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        agrirouter.response.payload.endpoint.Capability.CapabilityResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (agrirouter.response.payload.endpoint.Capability.CapabilityResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object applicationMessageId_ = "";
      /**
       * <pre>
       * Used for unique identification of the message for the application
       * </pre>
       *
       * <code>string application_message_id = 1;</code>
       */
      public java.lang.String getApplicationMessageId() {
        java.lang.Object ref = applicationMessageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          applicationMessageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Used for unique identification of the message for the application
       * </pre>
       *
       * <code>string application_message_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getApplicationMessageIdBytes() {
        java.lang.Object ref = applicationMessageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          applicationMessageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Used for unique identification of the message for the application
       * </pre>
       *
       * <code>string application_message_id = 1;</code>
       */
      public Builder setApplicationMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        applicationMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Used for unique identification of the message for the application
       * </pre>
       *
       * <code>string application_message_id = 1;</code>
       */
      public Builder clearApplicationMessageId() {
        
        applicationMessageId_ = getDefaultInstance().getApplicationMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Used for unique identification of the message for the application
       * </pre>
       *
       * <code>string application_message_id = 1;</code>
       */
      public Builder setApplicationMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        applicationMessageId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient> recipients_ =
        java.util.Collections.emptyList();
      private void ensureRecipientsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          recipients_ = new java.util.ArrayList<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient>(recipients_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder> recipientsBuilder_;

      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public java.util.List<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient> getRecipientsList() {
        if (recipientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recipients_);
        } else {
          return recipientsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public int getRecipientsCount() {
        if (recipientsBuilder_ == null) {
          return recipients_.size();
        } else {
          return recipientsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient getRecipients(int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);
        } else {
          return recipientsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder setRecipients(
          int index, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.set(index, value);
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder setRecipients(
          int index, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.set(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder addRecipients(agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder addRecipients(
          int index, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(index, value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder addRecipients(
          agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder addRecipients(
          int index, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder addAllRecipients(
          java.lang.Iterable<? extends agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient> values) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, recipients_);
          onChanged();
        } else {
          recipientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder clearRecipients() {
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public Builder removeRecipients(int index) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.remove(index);
          onChanged();
        } else {
          recipientsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder getRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder getRecipientsOrBuilder(
          int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);  } else {
          return recipientsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public java.util.List<? extends agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder> 
           getRecipientsOrBuilderList() {
        if (recipientsBuilder_ != null) {
          return recipientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recipients_);
        }
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder addRecipientsBuilder() {
        return getRecipientsFieldBuilder().addBuilder(
            agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.getDefaultInstance());
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder addRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().addBuilder(
            index, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.getDefaultInstance());
      }
      /**
       * <code>repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;</code>
       */
      public java.util.List<agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder> 
           getRecipientsBuilderList() {
        return getRecipientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder> 
          getRecipientsFieldBuilder() {
        if (recipientsBuilder_ == null) {
          recipientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.Recipient.Builder, agrirouter.response.payload.endpoint.Capability.CapabilityResponse.RecipientOrBuilder>(
                  recipients_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          recipients_ = null;
        }
        return recipientsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:agrirouter.response.payload.endpoint.CapabilityResponse)
    }

    // @@protoc_insertion_point(class_scope:agrirouter.response.payload.endpoint.CapabilityResponse)
    private static final agrirouter.response.payload.endpoint.Capability.CapabilityResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new agrirouter.response.payload.endpoint.Capability.CapabilityResponse();
    }

    public static agrirouter.response.payload.endpoint.Capability.CapabilityResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CapabilityResponse>
        PARSER = new com.google.protobuf.AbstractParser<CapabilityResponse>() {
      public CapabilityResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CapabilityResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CapabilityResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CapabilityResponse> getParserForType() {
      return PARSER;
    }

    public agrirouter.response.payload.endpoint.Capability.CapabilityResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4messaging/response/payload/endpoint/ca" +
      "pability.proto\022$agrirouter.response.payl" +
      "oad.endpoint\"\305\001\n\022CapabilityResponse\022\036\n\026a" +
      "pplication_message_id\030\001 \001(\t\022V\n\nrecipient" +
      "s\030\002 \003(\0132B.agrirouter.response.payload.en" +
      "dpoint.CapabilityResponse.Recipient\0327\n\tR" +
      "ecipient\022\n\n\002id\030\001 \001(\t\022\036\n\026technical_messag" +
      "e_type\030\002 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_descriptor,
        new java.lang.String[] { "ApplicationMessageId", "Recipients", });
    internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_descriptor =
      internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_descriptor.getNestedTypes().get(0);
    internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agrirouter_response_payload_endpoint_CapabilityResponse_Recipient_descriptor,
        new java.lang.String[] { "Id", "TechnicalMessageType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
