// source: messaging/response/payload/account/endpoints.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.agrirouter.response.payload.account.ListEndpointsResponse', null, global);
goog.exportSymbol('proto.agrirouter.response.payload.account.ListEndpointsResponse.Direction', null, global);
goog.exportSymbol('proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint', null, global);
goog.exportSymbol('proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.agrirouter.response.payload.account.ListEndpointsResponse.repeatedFields_, null);
};
goog.inherits(proto.agrirouter.response.payload.account.ListEndpointsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agrirouter.response.payload.account.ListEndpointsResponse.displayName = 'proto.agrirouter.response.payload.account.ListEndpointsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.displayName = 'proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.repeatedFields_, null);
};
goog.inherits(proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.displayName = 'proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.agrirouter.response.payload.account.ListEndpointsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    endpointsList: jspb.Message.toObjectList(msg.getEndpointsList(),
    proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agrirouter.response.payload.account.ListEndpointsResponse;
  return proto.agrirouter.response.payload.account.ListEndpointsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint;
      reader.readMessage(value,proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.deserializeBinaryFromReader);
      msg.addEndpoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agrirouter.response.payload.account.ListEndpointsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEndpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Direction = {
  SEND: 0,
  RECEIVE: 1,
  SEND_RECEIVE: 2
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.prototype.toObject = function(opt_includeInstance) {
  return proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.toObject = function(includeInstance, msg) {
  var f, obj = {
    technicalMessageType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    direction: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType;
  return proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTechnicalMessageType(value);
      break;
    case 2:
      var value = /** @type {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Direction} */ (reader.readEnum());
      msg.setDirection(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTechnicalMessageType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDirection();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string technical_message_type = 1;
 * @return {string}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.prototype.getTechnicalMessageType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.prototype.setTechnicalMessageType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Direction direction = 2;
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Direction}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.prototype.getDirection = function() {
  return /** @type {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Direction} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Direction} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.prototype.setDirection = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    endpointId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    endpointName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    endpointType: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, ""),
    messageTypesList: jspb.Message.toObjectList(msg.getMessageTypesList(),
    proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.toObject, includeInstance),
    externalId: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint;
  return proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndpointId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndpointName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndpointType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 5:
      var value = new proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType;
      reader.readMessage(value,proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.deserializeBinaryFromReader);
      msg.addMessageTypes(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEndpointId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEndpointName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEndpointType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMessageTypesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType.serializeBinaryToWriter
    );
  }
  f = message.getExternalId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string endpoint_id = 1;
 * @return {string}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.getEndpointId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.setEndpointId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string endpoint_name = 2;
 * @return {string}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.getEndpointName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.setEndpointName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string endpoint_type = 3;
 * @return {string}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.getEndpointType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.setEndpointType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string status = 4;
 * @return {string}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated MessageType message_types = 5;
 * @return {!Array<!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType>}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.getMessageTypesList = function() {
  return /** @type{!Array<!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType, 5));
};


/**
 * @param {!Array<!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType>} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} returns this
*/
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.setMessageTypesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.addMessageTypes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.agrirouter.response.payload.account.ListEndpointsResponse.MessageType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.clearMessageTypesList = function() {
  return this.setMessageTypesList([]);
};


/**
 * optional string external_id = 6;
 * @return {string}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.getExternalId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint.prototype.setExternalId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated Endpoint endpoints = 1;
 * @return {!Array<!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint>}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.prototype.getEndpointsList = function() {
  return /** @type{!Array<!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint, 1));
};


/**
 * @param {!Array<!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint>} value
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse} returns this
*/
proto.agrirouter.response.payload.account.ListEndpointsResponse.prototype.setEndpointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint}
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.prototype.addEndpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.agrirouter.response.payload.account.ListEndpointsResponse.Endpoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.agrirouter.response.payload.account.ListEndpointsResponse} returns this
 */
proto.agrirouter.response.payload.account.ListEndpointsResponse.prototype.clearEndpointsList = function() {
  return this.setEndpointsList([]);
};


goog.object.extend(exports, proto.agrirouter.response.payload.account);
