// source: messaging/request/request.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var commons_chunk_pb = require('../../commons/chunk_pb.js');
goog.object.extend(proto, commons_chunk_pb);
var commons_message_pb = require('../../commons/message_pb.js');
goog.object.extend(proto, commons_message_pb);
goog.exportSymbol('proto.agrirouter.request.RequestEnvelope', null, global);
goog.exportSymbol('proto.agrirouter.request.RequestEnvelope.Mode', null, global);
goog.exportSymbol('proto.agrirouter.request.RequestPayloadWrapper', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agrirouter.request.RequestEnvelope = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.agrirouter.request.RequestEnvelope.repeatedFields_, null);
};
goog.inherits(proto.agrirouter.request.RequestEnvelope, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agrirouter.request.RequestEnvelope.displayName = 'proto.agrirouter.request.RequestEnvelope';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.agrirouter.request.RequestPayloadWrapper = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.agrirouter.request.RequestPayloadWrapper, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.agrirouter.request.RequestPayloadWrapper.displayName = 'proto.agrirouter.request.RequestPayloadWrapper';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.agrirouter.request.RequestEnvelope.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agrirouter.request.RequestEnvelope.prototype.toObject = function(opt_includeInstance) {
  return proto.agrirouter.request.RequestEnvelope.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agrirouter.request.RequestEnvelope} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.request.RequestEnvelope.toObject = function(includeInstance, msg) {
  var f, obj = {
    applicationMessageId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    applicationMessageSeqNo: jspb.Message.getFieldWithDefault(msg, 2, 0),
    technicalMessageType: jspb.Message.getFieldWithDefault(msg, 3, ""),
    teamSetContextId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    mode: jspb.Message.getFieldWithDefault(msg, 5, 0),
    recipientsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    chunkInfo: (f = msg.getChunkInfo()) && commons_chunk_pb.ChunkComponent.toObject(includeInstance, f),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    metadata: (f = msg.getMetadata()) && commons_message_pb.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agrirouter.request.RequestEnvelope}
 */
proto.agrirouter.request.RequestEnvelope.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agrirouter.request.RequestEnvelope;
  return proto.agrirouter.request.RequestEnvelope.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agrirouter.request.RequestEnvelope} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agrirouter.request.RequestEnvelope}
 */
proto.agrirouter.request.RequestEnvelope.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplicationMessageId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setApplicationMessageSeqNo(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTechnicalMessageType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeamSetContextId(value);
      break;
    case 5:
      var value = /** @type {!proto.agrirouter.request.RequestEnvelope.Mode} */ (reader.readEnum());
      msg.setMode(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addRecipients(value);
      break;
    case 7:
      var value = new commons_chunk_pb.ChunkComponent;
      reader.readMessage(value,commons_chunk_pb.ChunkComponent.deserializeBinaryFromReader);
      msg.setChunkInfo(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 9:
      var value = new commons_message_pb.Metadata;
      reader.readMessage(value,commons_message_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agrirouter.request.RequestEnvelope.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agrirouter.request.RequestEnvelope.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agrirouter.request.RequestEnvelope} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.request.RequestEnvelope.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApplicationMessageId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApplicationMessageSeqNo();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getTechnicalMessageType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTeamSetContextId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMode();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getRecipientsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getChunkInfo();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      commons_chunk_pb.ChunkComponent.serializeBinaryToWriter
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      commons_message_pb.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.agrirouter.request.RequestEnvelope.Mode = {
  DIRECT: 0,
  PUBLISH: 1,
  PUBLISH_WITH_DIRECT: 2
};

/**
 * optional string application_message_id = 1;
 * @return {string}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getApplicationMessageId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.setApplicationMessageId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 application_message_seq_no = 2;
 * @return {number}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getApplicationMessageSeqNo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.setApplicationMessageSeqNo = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string technical_message_type = 3;
 * @return {string}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getTechnicalMessageType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.setTechnicalMessageType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string team_set_context_id = 4;
 * @return {string}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getTeamSetContextId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.setTeamSetContextId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Mode mode = 5;
 * @return {!proto.agrirouter.request.RequestEnvelope.Mode}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getMode = function() {
  return /** @type {!proto.agrirouter.request.RequestEnvelope.Mode} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.agrirouter.request.RequestEnvelope.Mode} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.setMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * repeated string recipients = 6;
 * @return {!Array<string>}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getRecipientsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.setRecipientsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.addRecipients = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.clearRecipientsList = function() {
  return this.setRecipientsList([]);
};


/**
 * optional agrirouter.commons.ChunkComponent chunk_info = 7;
 * @return {?proto.agrirouter.commons.ChunkComponent}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getChunkInfo = function() {
  return /** @type{?proto.agrirouter.commons.ChunkComponent} */ (
    jspb.Message.getWrapperField(this, commons_chunk_pb.ChunkComponent, 7));
};


/**
 * @param {?proto.agrirouter.commons.ChunkComponent|undefined} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
*/
proto.agrirouter.request.RequestEnvelope.prototype.setChunkInfo = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.clearChunkInfo = function() {
  return this.setChunkInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agrirouter.request.RequestEnvelope.prototype.hasChunkInfo = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp timestamp = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
*/
proto.agrirouter.request.RequestEnvelope.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agrirouter.request.RequestEnvelope.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional agrirouter.commons.Metadata metadata = 9;
 * @return {?proto.agrirouter.commons.Metadata}
 */
proto.agrirouter.request.RequestEnvelope.prototype.getMetadata = function() {
  return /** @type{?proto.agrirouter.commons.Metadata} */ (
    jspb.Message.getWrapperField(this, commons_message_pb.Metadata, 9));
};


/**
 * @param {?proto.agrirouter.commons.Metadata|undefined} value
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
*/
proto.agrirouter.request.RequestEnvelope.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agrirouter.request.RequestEnvelope} returns this
 */
proto.agrirouter.request.RequestEnvelope.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agrirouter.request.RequestEnvelope.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.agrirouter.request.RequestPayloadWrapper.prototype.toObject = function(opt_includeInstance) {
  return proto.agrirouter.request.RequestPayloadWrapper.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.agrirouter.request.RequestPayloadWrapper} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.request.RequestPayloadWrapper.toObject = function(includeInstance, msg) {
  var f, obj = {
    details: (f = msg.getDetails()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.agrirouter.request.RequestPayloadWrapper}
 */
proto.agrirouter.request.RequestPayloadWrapper.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.agrirouter.request.RequestPayloadWrapper;
  return proto.agrirouter.request.RequestPayloadWrapper.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.agrirouter.request.RequestPayloadWrapper} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.agrirouter.request.RequestPayloadWrapper}
 */
proto.agrirouter.request.RequestPayloadWrapper.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.agrirouter.request.RequestPayloadWrapper.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.agrirouter.request.RequestPayloadWrapper.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.agrirouter.request.RequestPayloadWrapper} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.agrirouter.request.RequestPayloadWrapper.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Any details = 1;
 * @return {?proto.google.protobuf.Any}
 */
proto.agrirouter.request.RequestPayloadWrapper.prototype.getDetails = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 1));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.agrirouter.request.RequestPayloadWrapper} returns this
*/
proto.agrirouter.request.RequestPayloadWrapper.prototype.setDetails = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.agrirouter.request.RequestPayloadWrapper} returns this
 */
proto.agrirouter.request.RequestPayloadWrapper.prototype.clearDetails = function() {
  return this.setDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.agrirouter.request.RequestPayloadWrapper.prototype.hasDetails = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.agrirouter.request);
