// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messaging/request/payload/endpoint/capabilities.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Agrirouter.Request.Payload.Endpoint {

  /// <summary>Holder for reflection information generated from messaging/request/payload/endpoint/capabilities.proto</summary>
  public static partial class CapabilitiesReflection {

    #region Descriptor
    /// <summary>File descriptor for messaging/request/payload/endpoint/capabilities.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CapabilitiesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVtZXNzYWdpbmcvcmVxdWVzdC9wYXlsb2FkL2VuZHBvaW50L2NhcGFiaWxp",
            "dGllcy5wcm90bxIjYWdyaXJvdXRlci5yZXF1ZXN0LnBheWxvYWQuZW5kcG9p",
            "bnQiuQQKF0NhcGFiaWxpdHlTcGVjaWZpY2F0aW9uEl0KDGNhcGFiaWxpdGll",
            "cxgBIAMoCzJHLmFncmlyb3V0ZXIucmVxdWVzdC5wYXlsb2FkLmVuZHBvaW50",
            "LkNhcGFiaWxpdHlTcGVjaWZpY2F0aW9uLkNhcGFiaWxpdHkSHAoUYXBwX2Nl",
            "cnRpZmljYXRpb25faWQYAiABKAkSJAocYXBwX2NlcnRpZmljYXRpb25fdmVy",
            "c2lvbl9pZBgDIAEoCRJwChllbmFibGVfcHVzaF9ub3RpZmljYXRpb25zGAQg",
            "ASgOMk0uYWdyaXJvdXRlci5yZXF1ZXN0LnBheWxvYWQuZW5kcG9pbnQuQ2Fw",
            "YWJpbGl0eVNwZWNpZmljYXRpb24uUHVzaE5vdGlmaWNhdGlvbhqHAQoKQ2Fw",
            "YWJpbGl0eRIeChZ0ZWNobmljYWxfbWVzc2FnZV90eXBlGAEgASgJElkKCWRp",
            "cmVjdGlvbhgCIAEoDjJGLmFncmlyb3V0ZXIucmVxdWVzdC5wYXlsb2FkLmVu",
            "ZHBvaW50LkNhcGFiaWxpdHlTcGVjaWZpY2F0aW9uLkRpcmVjdGlvbiI0CglE",
            "aXJlY3Rpb24SCAoEU0VORBAAEgsKB1JFQ0VJVkUQARIQCgxTRU5EX1JFQ0VJ",
            "VkUQAiJJChBQdXNoTm90aWZpY2F0aW9uEgwKCERJU0FCTEVEEAASCwoHRU5B",
            "QkxFRBABEhoKFkVOQUJMRURfSElHSF9GUkVRVUVOQ1kQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification), global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Parser, new[]{ "Capabilities", "AppCertificationId", "AppCertificationVersionId", "EnablePushNotifications" }, null, new[]{ typeof(global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction), typeof(global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Capability), global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Capability.Parser, new[]{ "TechnicalMessageType", "Direction" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CapabilitySpecification : pb::IMessage<CapabilitySpecification>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CapabilitySpecification> _parser = new pb::MessageParser<CapabilitySpecification>(() => new CapabilitySpecification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CapabilitySpecification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agrirouter.Request.Payload.Endpoint.CapabilitiesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CapabilitySpecification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CapabilitySpecification(CapabilitySpecification other) : this() {
      capabilities_ = other.capabilities_.Clone();
      appCertificationId_ = other.appCertificationId_;
      appCertificationVersionId_ = other.appCertificationVersionId_;
      enablePushNotifications_ = other.enablePushNotifications_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CapabilitySpecification Clone() {
      return new CapabilitySpecification(this);
    }

    /// <summary>Field number for the "capabilities" field.</summary>
    public const int CapabilitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Capability> _repeated_capabilities_codec
        = pb::FieldCodec.ForMessage(10, global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Capability.Parser);
    private readonly pbc::RepeatedField<global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Capability> capabilities_ = new pbc::RepeatedField<global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Capability>();
    /// <summary>
    /// List of supported capabilities. Would be a subset or all of those supported by the application
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Capability> Capabilities {
      get { return capabilities_; }
    }

    /// <summary>Field number for the "app_certification_id" field.</summary>
    public const int AppCertificationIdFieldNumber = 2;
    private string appCertificationId_ = "";
    /// <summary>
    /// Application ID from the agrirouter      
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppCertificationId {
      get { return appCertificationId_; }
      set {
        appCertificationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "app_certification_version_id" field.</summary>
    public const int AppCertificationVersionIdFieldNumber = 3;
    private string appCertificationVersionId_ = "";
    /// <summary>
    /// Application Certification Version ID from the agrirouter
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppCertificationVersionId {
      get { return appCertificationVersionId_; }
      set {
        appCertificationVersionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enable_push_notifications" field.</summary>
    public const int EnablePushNotificationsFieldNumber = 4;
    private global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification enablePushNotifications_ = global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification.Disabled;
    /// <summary>
    /// Enables/disables push notifications for the endpoint
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification EnablePushNotifications {
      get { return enablePushNotifications_; }
      set {
        enablePushNotifications_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CapabilitySpecification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CapabilitySpecification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!capabilities_.Equals(other.capabilities_)) return false;
      if (AppCertificationId != other.AppCertificationId) return false;
      if (AppCertificationVersionId != other.AppCertificationVersionId) return false;
      if (EnablePushNotifications != other.EnablePushNotifications) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= capabilities_.GetHashCode();
      if (AppCertificationId.Length != 0) hash ^= AppCertificationId.GetHashCode();
      if (AppCertificationVersionId.Length != 0) hash ^= AppCertificationVersionId.GetHashCode();
      if (EnablePushNotifications != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification.Disabled) hash ^= EnablePushNotifications.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      capabilities_.WriteTo(output, _repeated_capabilities_codec);
      if (AppCertificationId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AppCertificationId);
      }
      if (AppCertificationVersionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppCertificationVersionId);
      }
      if (EnablePushNotifications != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification.Disabled) {
        output.WriteRawTag(32);
        output.WriteEnum((int) EnablePushNotifications);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      capabilities_.WriteTo(ref output, _repeated_capabilities_codec);
      if (AppCertificationId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AppCertificationId);
      }
      if (AppCertificationVersionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppCertificationVersionId);
      }
      if (EnablePushNotifications != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification.Disabled) {
        output.WriteRawTag(32);
        output.WriteEnum((int) EnablePushNotifications);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += capabilities_.CalculateSize(_repeated_capabilities_codec);
      if (AppCertificationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppCertificationId);
      }
      if (AppCertificationVersionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppCertificationVersionId);
      }
      if (EnablePushNotifications != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification.Disabled) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EnablePushNotifications);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CapabilitySpecification other) {
      if (other == null) {
        return;
      }
      capabilities_.Add(other.capabilities_);
      if (other.AppCertificationId.Length != 0) {
        AppCertificationId = other.AppCertificationId;
      }
      if (other.AppCertificationVersionId.Length != 0) {
        AppCertificationVersionId = other.AppCertificationVersionId;
      }
      if (other.EnablePushNotifications != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification.Disabled) {
        EnablePushNotifications = other.EnablePushNotifications;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            capabilities_.AddEntriesFrom(input, _repeated_capabilities_codec);
            break;
          }
          case 18: {
            AppCertificationId = input.ReadString();
            break;
          }
          case 26: {
            AppCertificationVersionId = input.ReadString();
            break;
          }
          case 32: {
            EnablePushNotifications = (global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            capabilities_.AddEntriesFrom(ref input, _repeated_capabilities_codec);
            break;
          }
          case 18: {
            AppCertificationId = input.ReadString();
            break;
          }
          case 26: {
            AppCertificationVersionId = input.ReadString();
            break;
          }
          case 32: {
            EnablePushNotifications = (global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.PushNotification) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CapabilitySpecification message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Specifies which way the messages are to flow for the capabilities when sending the message this shoudl be aligned with the application certification
      /// </summary>
      public enum Direction {
        [pbr::OriginalName("SEND")] Send = 0,
        [pbr::OriginalName("RECEIVE")] Receive = 1,
        [pbr::OriginalName("SEND_RECEIVE")] SendReceive = 2,
      }

      public enum PushNotification {
        [pbr::OriginalName("DISABLED")] Disabled = 0,
        [pbr::OriginalName("ENABLED")] Enabled = 1,
        [pbr::OriginalName("ENABLED_HIGH_FREQUENCY")] EnabledHighFrequency = 2,
      }

      public sealed partial class Capability : pb::IMessage<Capability>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Capability> _parser = new pb::MessageParser<Capability>(() => new Capability());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Capability> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Capability() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Capability(Capability other) : this() {
          technicalMessageType_ = other.technicalMessageType_;
          direction_ = other.direction_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Capability Clone() {
          return new Capability(this);
        }

        /// <summary>Field number for the "technical_message_type" field.</summary>
        public const int TechnicalMessageTypeFieldNumber = 1;
        private string technicalMessageType_ = "";
        /// <summary>
        /// Technical Message type from agrirouter
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TechnicalMessageType {
          get { return technicalMessageType_; }
          set {
            technicalMessageType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "direction" field.</summary>
        public const int DirectionFieldNumber = 2;
        private global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction direction_ = global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction.Send;
        /// <summary>
        /// Specifies which way the messages are to flow for the capability
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction Direction {
          get { return direction_; }
          set {
            direction_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Capability);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Capability other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (TechnicalMessageType != other.TechnicalMessageType) return false;
          if (Direction != other.Direction) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (TechnicalMessageType.Length != 0) hash ^= TechnicalMessageType.GetHashCode();
          if (Direction != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction.Send) hash ^= Direction.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (TechnicalMessageType.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(TechnicalMessageType);
          }
          if (Direction != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction.Send) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Direction);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (TechnicalMessageType.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(TechnicalMessageType);
          }
          if (Direction != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction.Send) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Direction);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (TechnicalMessageType.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TechnicalMessageType);
          }
          if (Direction != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction.Send) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Direction);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Capability other) {
          if (other == null) {
            return;
          }
          if (other.TechnicalMessageType.Length != 0) {
            TechnicalMessageType = other.TechnicalMessageType;
          }
          if (other.Direction != global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction.Send) {
            Direction = other.Direction;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                TechnicalMessageType = input.ReadString();
                break;
              }
              case 16: {
                Direction = (global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction) input.ReadEnum();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                TechnicalMessageType = input.ReadString();
                break;
              }
              case 16: {
                Direction = (global::Agrirouter.Request.Payload.Endpoint.CapabilitySpecification.Types.Direction) input.ReadEnum();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
