name: Continuous integration

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  build_jdk8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B package --file java/pom.xml --settings java/ci/settings.xml
  build_dotnet:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Build solution and generate NuGet package
        run: |
          cd .\dotnet\AgrirouterApiProtobufDefinitions\
          dotnet pack -c Release -o out