name: Continuous delivery

on:
  push:
    branches:
      - develop

jobs:
  deploy_maven_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B deploy --file java/pom.xml --settings java/ci/settings.xml