name: Push NuGet Packages

on:
  push:
    branches:
      - 'releases/dotnet/*'

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build solution and generate NuGet package
        run: |
          cd .\dotnet\AgrirouterApiProtobufDefinitions\
          dotnet pack -c Release -o out

      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/DKE-Data/index.json -Username DKE-Data -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package to GitHub registry
        run: nuget push .\dotnet\AgrirouterApiProtobufDefinitions\out\*.nupkg -Source "GPR" -SkipDuplicate
