name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_maven_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B deploy --file java/pom.xml --settings java/ci/settings.xml
  deploy_nuget_packages:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Build solution and generate NuGet package
        run: |
          cd .\dotnet\AgrirouterApiProtobufDefinitions\
          dotnet pack -c Release -o out
      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/DKE-Data/index.json -Username DKE-Data -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText
      - name: Push generated package to GitHub registry
        run: nuget push .\dotnet\AgrirouterApiProtobufDefinitions\out\*.nupkg -Source "GPR" -SkipDuplicate